{% set name = "openff-models" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openforcefield/openff-models/archive/{{ version }}.tar.gz
  sha256: 7a2df4ced8724cf18460b730d5df34e8f7731d8b08e4186afb9b974d5d52b561

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.8
    - numpy
    - pydantic <2.0.0a0
    - openff-units
    - openff-utilities
  run_constrained:
    - openmm >=7.6

test:
  imports:
    - openff.models

about:
  home: https://openforcefield.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Helper classes for Pydantic compatibility in the OpenFF stack
  dev_url: https://github.com/openforcefield/openff-models

extra:
  recipe-maintainers:
    - mattwthompson
    - j-wags
