{% set name = "openff-models" %}
{% set version = "0.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openforcefield/openff-models/archive/{{ version }}.tar.gz
  sha256: 9127dc4f6448e0c5f442bcb296813f26427fe5935446fa3349d5541144ada325

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.8
    - numpy
    - pydantic <2.0.0a0
    - openff-units
    - openff-utilities
    - openmm

test:
  imports:
    - openff.models

about:
  home: https://openforcefield.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Helper classes for Pydantic compatibility in the OpenFF stack
  dev_url: https://github.com/openforcefield/openff-models

extra:
  recipe-maintainers:
    - mattwthompson
