{% set name = "openff-models" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openforcefield/openff-models/archive/{{ version }}.tar.gz
  sha256: 9e7c8b5b5840ec5cf540877830252db197cfdd08354780c500f7d345276eca39

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.9
    - numpy =1
    - pydantic >=1.8.2
    - openff-units
    - openff-utilities
  run_constrained:
    - openmm >=7.6

test:
  imports:
    - openff.models
  files:
    - test_openff_models.py
  commands:
    - python test_openff_models.py


about:
  home: https://openforcefield.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Helper classes for Pydantic compatibility in the OpenFF stack
  dev_url: https://github.com/openforcefield/openff-models

extra:
  recipe-maintainers:
    - mattwthompson
    - j-wags
