{% set name = "openff-models" %}
{% set version = "0.1.0beta0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openforcefield/openff-models/archive/{{ version }}.tar.gz
  sha256: c97168a8c5c49ca3e7e5d60c87c1a6e7cc602f27815f3728998412458fa95d26

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.9
    - numpy =1
    - pydantic >=1.8.2
    - openff-units
    - openff-utilities
  run_constrained:
    - openmm >=7.6

test:
  imports:
    - openff.models

about:
  home: https://openforcefield.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Helper classes for Pydantic compatibility in the OpenFF stack
  dev_url: https://github.com/openforcefield/openff-models

extra:
  recipe-maintainers:
    - mattwthompson
    - j-wags
